const fs = require("fs");
const path = require("path");
const axios = require("axios");
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

async function run() {

  if (!fs.existsSync("data.json")) return;

  const data = JSON.parse(fs.readFileSync("data.json"));

  const top5 = data.slice(0, 5);

  // find a snapshot closest to 7 days ago
  const snapshotsDir = path.join(__dirname, "snapshots");
  let weekSnapshot = null;

  if (fs.existsSync(snapshotsDir)) {
    const files = fs.readdirSync(snapshotsDir).filter(f => f.endsWith('.json'));
    if (files.length > 0) {
      const targetDate = new Date();
      targetDate.setDate(targetDate.getDate() - 7);

      // choose file with date closest to targetDate
      let best = null;
      let bestDiff = Infinity;
      files.forEach(f => {
        const datePart = f.slice(0, 10);
        const d = new Date(datePart);
        if (isNaN(d)) return;
        const diff = Math.abs(d - targetDate);
        if (diff < bestDiff) {
          bestDiff = diff;
          best = f;
        }
      });

      if (best) {
        try {
          weekSnapshot = JSON.parse(fs.readFileSync(path.join(snapshotsDir, best)));
        } catch (e) {
          weekSnapshot = null;
        }
      }
    }
  }

  // helper to compute percent change
  function pctChange(oldVal, newVal) {
    if (!oldVal || oldVal === 0) return null;
    return ((newVal - oldVal) / oldVal) * 100;
  }

  // build rows with percent change when available
  const rowsHtml = top5.map((x, i) => {
    const prev = weekSnapshot ? weekSnapshot.find(s => s.SecurityID === x.SecurityID) : null;
    const change = prev ? pctChange(prev.mcap, x.mcap) : null;
    let changeHtml = '—';
    if (change !== null) {
      const sign = change >= 0 ? '▲' : '▼';
      const color = change >= 0 ? '#198754' : '#dc3545';
      changeHtml = `<span style="color:${color};font-weight:600;">${sign} ${Math.abs(change).toFixed(2)}%</span>`;
    }

    return `
      <tr>
        <td style="padding:10px;border:1px solid #ddd;text-align:center;">${i + 1}</td>
        <td style="padding:10px;border:1px solid #ddd;">${x.name}</td>
        <td style="padding:10px;border:1px solid #ddd;">${Number(x.mcap).toLocaleString()}</td>
        <td style="padding:10px;border:1px solid #ddd;text-align:center;">${changeHtml}</td>
      </tr>
    `;
  }).join("");

// 📊 HTML EMAIL (Bootstrap-like styling)
const html = `
<div style="font-family: Arial, sans-serif; background:#f4f6f9; padding:20px;">

  <div style="max-width:600px;margin:auto;background:white;border-radius:10px;overflow:hidden;box-shadow:0 4px 10px rgba(0,0,0,0.1);">

    <div style="background:#0d6efd;color:white;padding:15px;text-align:center;font-size:20px;font-weight:bold;">
      📊 Weekly Stock Summary
    </div>

    <div style="padding:20px;">
      <p style="font-size:14px;color:#555;">
        Here is your <b>Top 5 Companies</b> ranking update for this week:
      </p>

      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#f1f1f1;">
            <th style="padding:10px;border:1px solid #ddd;">Rank</th>
            <th style="padding:10px;border:1px solid #ddd;">Company</th>
            <th style="padding:10px;border:1px solid #ddd;">Market Cap</th>
            <th style="padding:10px;border:1px solid #ddd;">Change (7d)</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>

      <p style="margin-top:20px;font-size:12px;color:#888;">
        Auto-generated by Stock Tracker System 🚀
      </p>
    </div>

  </div>
</div>
`;

await transporter.sendMail({
  from: process.env.EMAIL_USER,
  to: process.env.TO_EMAIL_LIST,
  subject: "📊 Weekly Stock Summary Report",
  html: html
});

}

run();
