const fs = require("fs");
const axios = require("axios");
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

async function run() {

  if (!fs.existsSync("data.json")) return;

  const data = JSON.parse(fs.readFileSync("data.json"));

  const top5 = data.slice(0, 5);

  // 📊 HTML EMAIL (Bootstrap-like styling)
  const html = `
  <div style="font-family: Arial, sans-serif; background:#f4f6f9; padding:20px;">
    
    <div style="max-width:600px;margin:auto;background:white;border-radius:10px;overflow:hidden;box-shadow:0 4px 10px rgba(0,0,0,0.1);">
      
      <div style="background:#0d6efd;color:white;padding:15px;text-align:center;font-size:20px;font-weight:bold;">
        📊 Weekly Stock Summary
      </div>

      <div style="padding:20px;">
        <p style="font-size:14px;color:#555;">
          Here is your <b>Top 5 Companies</b> ranking update for this week:
        </p>

        <table style="width:100%;border-collapse:collapse;">
          <thead>
            <tr style="background:#f1f1f1;">
              <th style="padding:10px;border:1px solid #ddd;">Rank</th>
              <th style="padding:10px;border:1px solid #ddd;">Company</th>
              <th style="padding:10px;border:1px solid #ddd;">Market Cap</th>
            </tr>
          </thead>
          <tbody>
            ${top5.map((x, i) => `
              <tr>
                <td style="padding:10px;border:1px solid #ddd;text-align:center;">${i + 1}</td>
                <td style="padding:10px;border:1px solid #ddd;">${x.name}</td>
                <td style="padding:10px;border:1px solid #ddd;">${x.mcap.toLocaleString()}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>

        <p style="margin-top:20px;font-size:12px;color:#888;">
          Auto-generated by Stock Tracker System 🚀
        </p>
      </div>

    </div>
  </div>
  `;

  await transporter.sendMail({
    from: process.env.EMAIL_USER,
    to: process.env.TO_EMAIL_LIST,
    subject: "📊 Weekly Stock Summary Report",
    html: html
  });

}

run();
